import Head from "next/head";
import { gql } from "@apollo/client";
import Image from "next/image";
import { useState } from "react";
import { useQuery } from "@apollo/client/react";
import SelectBar from "./Select";
import Getdoog from "./Getdoog";

export default function Home() {
  const [country_code, setcountry_code] = useState("IN");

  function setcode(value: any) {
    setcountry_code(value);
  }
  // const GET_LOCATION = gql`
  //   query GetLocations {
  //     locations {
  //       id
  //       name
  //       description
  //       photo
  //     }
  //   }
  // `;
  const GET_COUNTRY = gql`
    query Query {
      country(code: "${country_code}") {
        name
        native
        capital
        emoji
        currency
        languages {
          code
          name
        }
      }
    }
  `;
  const { loading: load, error: er, data: dt } = useQuery(GET_COUNTRY);
  console.log(dt);

  if (load) return "Loading...";
  if (er) return `Error! ${er.message}`;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SelectBar setcode={setcode} />
        <p className="title">selected country code : {country_code}</p>
        <div className="card-container">
          <div className="card">
            <p className="title">{dt?.country?.capital}</p>
            {dt.country.languages.map((languages: any) => {
              return (
                <>
                  <p className="desc">{languages.__typename}</p>
                  <p className="desc">{languages.name}</p>
                  <p className="desc">{languages.code}</p>
                </>
              );
            })}
          </div>
        </div>

        {/* <Getdoog /> */}
      </main>
    </>
  );
}
