import Head from "next/head";
import { gql } from "@apollo/client";
import client from "@/lib/apollo-client";
import Image from "next/image";
import { useQuery } from "@apollo/client/react";

export default function Home() {
  const GET_LOCATION = gql`
    query GetLocations {
      locations {
        id
        name
        description
        photo
      }
    }
  `;
  const { loading, error, data } = useQuery(GET_LOCATION);
  if (loading) return "Loading...";
  if (error) return `Error! ${error.message}`;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="card-container">
          {data.locations.map((location: any) => (
            <div className="card" key={location.id}>
              <p className="title">{location.name}</p>
              <p className="desc">{location.description.slice(0, 200)}...</p>
              <Image
                src={`${location.photo}`}
                width={50}
                height={50}
                alt="photo"
                unoptimized
                className="photo"
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
// SSR
// export async function getStaticProps() {
//   const { data } = await client.query({
//     query: gql`
//       query GetLocations {
//         locations {
//           id
//           name
//           description
//           photo
//         }
//       }
//     `,
//   });
//   return {
//     props: {
//       nextLocation: data.locations,
//     },
//   };
// }
